apiVersion: apps/v1
kind: Deployment
metadata:
  name:
    migration-interface
  labels:
    app: 
      migration-interface
  namespace:
    default
  annotations:
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: migration-interface
  template:
    metadata:
      labels:
        app: migration-interface
      annotations:
        migration-bypass: 'True'
    spec:
      serviceAccountName: migration-interface
      containers:
        - name: interface
          image: ghcr.io/tynonyuhn/migration-interface:main
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: REACT_APP_GKE_IP
              value: '34.171.128.48'
            - name: REACT_APP_AKS_IP
              value: '20.121.139.124'
#         startupProbe:
#           httpGet:
#             port: 5001
#         livenessProbe:
#           httpGet:
#             port: 5001
          
---
apiVersion: v1
kind: Service
metadata:
  name: interface-node-port
  labels:
    app: migration-interface
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  selector:
    app: migration-interface
