
apiVersion: v1
kind: Deployment
metadata:
  name: memhog
  labels:
    app: memhog
#  namespace: myproject
  annotations:
    migration-interface: 'dind'
#     migration-start-mode: 'null'
spec:
  replicas: 10
  serviceAccountName: migration-coordinator
  template:
    containers:
      - name: memhog
        image: ghcr.io/hpcclab/live_service_migration/memhog:main
        env:
          - name: MEMORY_LIMIT
            value: '128'
          - name: MEMORY_INCREMENT
            value: '128'
          # - name: PATTERN
          #   value: migration
